
CREATE TABLE ads
(
    ad_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ad_title        VARCHAR(32)  NOT NULL,
    ad_description  VARCHAR(255) NOT NULL,
    ad_price        INTEGER      NOT NULL,
    user_id         INTEGER      NOT NULL,
    image_id        VARCHAR(255)      NOT NULL,

    FOREIGN KEY (user_id) REFERENCES users (user_id)

);