
CREATE TABLE ads
(
    ad_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ad_title        VARCHAR(40)  NOT NULL,
    ad_description  VARCHAR(500) NOT NULL,
    ad_price        INTEGER      NOT NULL,
    user_id         INTEGER      NOT NULL,
    image_id        INTEGER      NOT NULL,

    FOREIGN KEY (user_id) REFERENCES users (user_id),
    FOREIGN KEY (image_id) REFERENCES image (image_id)

);